#!/bin/sh

REACT_APP_SUPABASE_URL=https://sfmxpirlxttmsayswdkt.supabase.co
REACT_APP_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmbXhwaXJseHR0bXNheXN3ZGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDc5NTU3NzMsImV4cCI6MTk2MzUzMTc3M30.vhbTuicW8oPZFuoOt8V9HqXVExNEK3J-95yRLw-gquo

npx openapi-typescript "${REACT_APP_SUPABASE_URL}"/rest/v1/?apikey="${REACT_APP_SUPABASE_ANON_KEY}" --output types/supabase.ts